### ISSUE TITLE
Issue #1: Add Missing logo here and if the logo is not available then add a popular country from that continent

### ISSUE THREAD

**Issue by Siddheshuncodes** [Swifty9/Maverick-AI#37]
![image](https://github.com/user-attachments/assets/bc021d0a-7ff9-415c-8701-155602677dd3)
- [x] Add the Proper official Logo of the country 
- [x] Add proper description for the country

**Comment by hrutikkharjul** [comment]
I've implemented the changes and created a pull request. Please assign this to me.
