### ISSUE TITLE
Issue #14 Enable Multiple option to download of Report 

### ISSUE THREAD

**Issue by Siddheshuncodes** [Swifty9/Maverick-AI#59]
![image](https://github.com/user-attachments/assets/0eb59cf9-3fd0-4f61-92e3-9f26d57219bd)
Currently, the reports are only downloaded in TXT format 

What we want is for someone to click on the Download Button and have a drop-down menu to select the format they want to download in.

Currently, we need PDF format and TXT format. 

![image](https://github.com/user-attachments/assets/3d09f348-c669-487f-a006-35a26c9bb020)

**Comment by pradnyabhukan** [comment]
Hi @Siddheshuncodes, I would like to work on this issue. Can you assign this to me?
