### ISSUE TITLE
Issue #16 - Improve the footer of the website

### ISSUE THREAD

**Issue by divyesh-mali** [Swifty9/Maverick-AI#73]
![image](https://github.com/user-attachments/assets/341685cc-1f2f-4700-8505-d6c21be9d12b)

**Description**:
Design and develop a good looking footer page and align it properly at the bottom of the page.

**Tasks**:
- [x] Design and improve footer page with proper styling.
- [x] Ensure responsive design

**Technical Requirements**:
- React components

**Comment by cduarte3** [comment]
Hi @divyesh-mali, can I please be assigned to this issue? As well, do you have anything in mind to implement for design, or am I free to create and update you with design choice?

**Comment by divyesh-mali** [comment]
@cduarte3 Thank you for taking up this issue. There are no hard and fast rules for designing. Just make sure it matches with the color theme of website and is responsive to mobile device as well.

**Comment by Siddheshuncodes** [comment]
@cduarte3 Hey, any update on this issue?

**Comment by cduarte3** [comment]
@Siddheshuncodes

Yes, I have drafted up a design and am currently working on implementation.

My mockup is as below:

![image](https://github.com/user-attachments/assets/de7a0854-2525-477c-84be-1f0e4a388806)

**Comment by divyesh-mali** [comment]
The design looks great! Looking forward to your PR. 👍

**Comment by cduarte3** [comment]
PR opened at https://github.com/Swifty9/Maverick-AI/pull/96

**Comment by Siddheshuncodes** [comment]
Thanks for your contribution you did great work.
We will be sharing contributors of Maverick AI on our social media platforms can you please share your details regarding LinkedIn and X(Twitter)?

**Comment by cduarte3** [comment]
No problem, was happy to contribute to the project !

### LinkedIn:
www.linkedin.com/in/christian-duarte-97593329b

### Twitter (Not as Active):
https://x.com/c_duarte718?s=21

### Dev.to Blog:
https://dev.to/cduarte3

**Comment by Siddheshuncodes** [comment]
Thanks for sharing we will mention you in the post for next week.
