### ISSUE TITLE
Issue: #18 Layout Shift on Hamburger Icon Click

### ISSUE THREAD

**Issue by Jayesh-Kr** [Swifty9/Maverick-AI#76]
https://github.com/user-attachments/assets/52138d31-4eb2-4525-b7a4-d727f94b1aa5

Description: When the user clicks on the hamburger icon, there is a sudden shift in the layout, causing a poor user experience. The layout movement appears abrupt, making it less smooth and visually unappealing.

Expected Behavior: Clicking the hamburger icon should trigger a smooth transition, where the layout shifts gradually, creating a more polished and pleasant experience for the user.

Steps to Reproduce:
-> Open the application/website.
-> Click on the hamburger icon.
-> Observe the sudden shift in layout.

Suggested Solution:
-> Implement a smooth CSS transition for the elements that shift when the hamburger menu is toggled.
-> This could include transitions on positioning, width, or opacity, depending on the layout.

Impact:
-> Negative impact on user experience due to abrupt layout changes.
-> Could affect the overall visual design and feel of the application/website.

**Comment by Jayesh-Kr** [comment]
@Siddheshuncodes @MehulPardeshi Can I work on this issue

**Comment by divyesh-mali** [comment]
Yes you can work on it @Jayesh-Kr

**Comment by Siddheshuncodes** [comment]
Thanks for this issue I have Assigned you this issue to start working on it and if you have any issues then ping me.
