### ISSUE TITLE
Issue #24 Issue with drop down menu for mobile version

### ISSUE THREAD

**Issue by Siddheshuncodes** [Swifty9/Maverick-AI#84]
![image](https://github.com/user-attachments/assets/f803ff01-8c75-4f8b-b216-d260c9a90622)
When you try to Download a report on the Phone UI the background looks transparent.

- [x] Add proper background colour which properly goes with the theme.
- [x] Add proper style so it is responsive

**Comment by patricksolka** [comment]
hey @Siddheshuncodes would love to work on this! Could you assign it to me?

**Comment by Siddheshuncodes** [comment]
Sorry for your inconvenience this issue has been resolved you can go through and for other issues you will find a bunch of good first issues are still creating some new issues
